"""empty message

Revision ID: 19b7f550340c
Revises: 5f0acff699f4
Create Date: 2018-09-11 21:45:49.587185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b7f550340c'
down_revision = '5f0acff699f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('last_active', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'last_active')
    # ### end Alembic commands ###
