"""empty message

Revision ID: 5f0acff699f4
Revises: 786a305ec6ff
Create Date: 2018-09-11 14:00:06.263241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0acff699f4'
down_revision = '786a305ec6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rota')
    # ### end Alembic commands ###
